const clientslogo = [
  {
    id: 1,
    img: "../images/clients_logo/1.png",
    alt: "logo1",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 2,
    img: "../images/clients_logo/2.png",
    alt: "logo2",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 3,
    img: "../images/clients_logo/3.png",
    alt: "logo3",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 4,
    img: "../images/clients_logo/4.png",
    alt: "logo4",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 5,
    img: "../images/clients_logo/5.png",
    alt: "logo5",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 6,
    img: "../images/clients_logo/6.png",
    alt: "logo6",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 7,
    img: "../images/clients_logo/7.png",
    alt: "logo7",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 8,
    img: "../images/clients_logo/8.png",
    alt: "logo8",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 9,
    img: "../images/clients_logo/9.png",
    alt: "logo9",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 10,
    img: "../images/clients_logo/10.png",
    alt: "logo10",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 11,
    img: "../images/clients_logo/11.png",
    alt: "logo11",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 12,
    img: "../images/clients_logo/12.png",
    alt: "logo12",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 13,
    img: "../images/clients_logo/13.png",
    alt: "logo13",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 14,
    img: "../images/clients_logo/14.png",
    alt: "logo14",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 15,
    img: "../images/clients_logo/15.png",
    alt: "logo15",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 16,
    img: "../images/clients_logo/16.png",
    alt: "logo16",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 17,
    img: "../images/clients_logo/17.png",
    alt: "logo17",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 18,
    img: "../images/clients_logo/49.png",
    alt: "logo18",
  },
  {
    id: 19,
    img: "../images/clients_logo/19.png",
    alt: "logo19",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 20,
    img: "../images/clients_logo/20.png",
    alt: "logo20",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 21,
    img: "../images/clients_logo/21.png",
    alt: "logo21",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 22,
    img: "../images/clients_logo/23.png",
    alt: "logo23",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 24,
    img: "../images/clients_logo/24.png",
    alt: "logo24",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 25,
    img: "../images/clients_logo/25.png",
    alt: "logo25",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 26,
    img: "../images/clients_logo/26.png",
    alt: "logo26",
    title: "Hello",
    discription: "ffd",
  },

  {
    id: 27,
    img: "../images/clients_logo/27.png",
    alt: "logo27",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 28,
    img: "../images/clients_logo/28.png",
    alt: "logo28",
  },
  {
    id: 29,
    img: "../images/clients_logo/29.png",
    alt: "logo29",
  },
  {
    id: 30,
    img: "../images/clients_logo/30.png",
    alt: "logo30",
  },
  {
    id: 31,
    img: "../images/clients_logo/31.png",
    alt: "logo31",
  },
  {
    id: 32,
    img: "../images/clients_logo/32.png",
    alt: "logo32",
  },
  {
    id: 33,
    img: "../images/clients_logo/33.png",
    alt: "logo33",
  },
  {
    id: 34,
    img: "../images/clients_logo/34.png",
    alt: "logo34",
  },
  {
    id: 35,
    img: "../images/clients_logo/67.png",
    alt: "logo35",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 36,
    img: "../images/clients_logo/36.png",
    alt: "logo36",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 37,
    img: "../images/clients_logo/37.png",
    alt: "logo37",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 38,
    img: "../images/clients_logo/38.png",
    alt: "logo38",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 39,
    img: "../images/clients_logo/39.png",
    alt: "logo39",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 40,
    img: "../images/clients_logo/40.png",
    alt: "logo40",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 41,
    img: "../images/clients_logo/41.png",
    alt: "logo41",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 42,
    img: "../images/clients_logo/42.png",
    alt: "logo42",
  },
  {
    id: 43,
    img: "../images/clients_logo/43.png",
    alt: "logo43",
  },
  {
    id: 44,
    img: "../images/clients_logo/44.png",
    alt: "logo44",
  },
  {
    id: 45,
    img: "../images/clients_logo/45.png",
    alt: "logo45",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 46,
    img: "../images/clients_logo/46.png",
    alt: "logo46",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 47,
    img: "../images/clients_logo/47.png",
    alt: "logo47",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 48,
    img: "../images/clients_logo/48.png",
    alt: "logo48",
    title: "Hello",
    discription: "ffd",
  },
  {
    id: 49,
    img: "../images/clients_logo/50.png",
    alt: "logo26",
    title: "Hello",
    discription: "ffd",
  },
];

export default clientslogo;
