import Head from "next/head";

import Ourservices from "@/components/ourServices";
import City from "@/components/cityList";
import Enquire from "@/components/enquire/enquire";
import Searchmedia from "@/components/searchMedia";
import Trendingcity from "@/components/trendingcity";
import Footer from "@/components/footer";

export default function Home() {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
   <Searchmedia/>
        </section>
        <section>
          <Ourservices/>
        </section>
        <section>
          <City/>
        </section>
        <section>
          <Enquire/>
        </section>
        <section>
          <Trendingcity/>
        </section>
        <Footer/>
      </main>
    </>
  );
}  
